#services:
#  mongodb:
#    image: mongo
#    container_name: mongo_db_chess
#    ports:
#      - 27017:27017
#    volumes:
#      - mongo:/data
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=chess
#      - MONGO_INITDB_ROOT_PASSWORD=chess
#
#  mongo-express:
#    image: mongo-express
#    container_name: mongo_express_chess
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=chess
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=chess
#      - ME_CONFIG_MONGODB_SERVER=mongodb
#volumes:
#  mongo: